### ISSUE TITLE
Release into kinetic

### ISSUE THREAD

**Issue by davetcoleman** [ros-interactive-manipulation/household_objects_database_msgs#3]
MoveIt! depends on this package https://github.com/ros-planning/moveit_ros/issues/695

**Comment by davetcoleman** [comment]
ping @tfoote @isucan need help releasing this

**Comment by davetcoleman** [comment]
@130s since you're already doing a great job with releasing moveit debians, think you could release these also?

**Comment by 130s** [comment]
Work is in progress #4

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/12199
