### ISSUE TITLE
Release into ROS Lunar

### ISSUE THREAD

**Issue by 130s** [ros-interactive-manipulation/household_objects_database_msgs#5]
This package [blocks some packages](http://repositories.ros.org/status_page/blocked_releases_lunar.html?s=6&r=1) incl. MoveIt!.

**Comment by 130s** [comment]
Prerelease test for Lunar run locally seems successful. I'll make a new release.

```
$ mkdir /tmp/prtest_householdobmsgs_lunar
$ cd /tmp/prtest_householdobmsgs_lunar
$ generate_prerelease_script.py   https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml lunar default ubuntu xenial amd64 --level 0 --custom-repo household_objects_database_msgs:git:https://github.com/ros-interactive-manipulation/household_objects_database_msgs:hydro-devel --output-dir ./
$ ./prerelease.sh 
:
Test results of underlay workspace
Invoking: catkin_test_results /tmp/prtest_householdobmsgs_lunar/catkin_workspace/test_results --all
Summary: 0 tests, 0 errors, 0 failures, 0 skipped

Skipping empty overlay workspace
```

**Comment by 130s** [comment]
https://github.com/ros/rosdistro/pull/14647

**Comment by v4hn** [comment]
To the best of my knowledge, this package is deprecated and in my opinion should not have been released into lunar anymore.

See https://github.com/ros-interactive-manipulation/manipulation_msgs/issues/9 and https://github.com/ros-planning/moveit/commit/29564393260a8d5bac41eb036aedb282149fffa2

**Comment by 130s** [comment]
Thanks. Since I already released this package into Lunar, I prefer to leaving it there as it is, but I added a deprecation note on [wiki](http://wiki.ros.org/action/info/household_objects_database_msgs?action=diff&rev2=5&rev1=4) and the top page of this repo.

**Comment by v4hn** [comment]
Thanks for all your work on this!

**Comment by davetcoleman** [comment]
Yes, thanks @130s !

Why did it say moveit depended on household_objects_database_msgs? I don't see any references in the moveit code...

**Comment by 130s** [comment]
> Why did it say moveit depended on household_objects_database_msgs?

I don't know what [repositories.ros.org/status_page page](http://repositories.ros.org/status_page/blocked_releases_lunar.html?s=6&r=1) refers to, but I found the dependency in `jade-devel` [here](https://github.com/ros-planning/moveit/blob/5cc9f6d341195cb8d45ebc7ac70aa43d69537969/moveit_ros/manipulation/package.xml#L32). `indigo-devel` too. In `kinetic-devel` it's removed https://github.com/ros-planning/moveit/pull/328. 
(The page above may trace back to non-latest distros to figure out the dependency?)

 I assume if we want to remove these dependency in MoveIt! for IJ, we also need the change in source like https://github.com/ros-planning/moveit/pull/328 does.

**Comment by v4hn** [comment]
On Wed, Apr 26, 2017 at 02:02:05PM -0700, Isaac I.Y. Saito wrote:
>  I assume if we want to remove these dependency in MoveIt! for IJ

We don't. This should be kept as is to retain the current behavior there.
There has been some discussion on this in the past.

**Comment by 130s** [comment]
Ok.

Fyi I just asked https://github.com/ros-infrastructure/ros_buildfarm/issues/428 for clarification for the status page.

**Comment by mikaelarguedas** [comment]
As mentioned in https://github.com/ros-infrastructure/ros_buildfarm/issues/428 the blocked_release status_page refers only to the previous distro. It's odd that household_objects_database_msgs showed as a dependency of the moveit repo though and should be investigated.

Regarding the status of household_objects_database_msgs: This package doesnt seem to be used by anything in kinetic and I think it's sensible to remove it from Lunar even if it has been released already. 
- If you decide to remove it: it will also have the advantage of seeing how the status page behaves regarding moveit dependency on it.
- If you decide not to remove it: please run bloom updating the status of the package as end-of-life so that we avoid being in the same situation for the next ROS release.

**Comment by 130s** [comment]
@mikaelarguedas thanks for the headsup, I agree to remove from Lunar so that we'll be able to see on the status page again how this package is depended on. 
Opened a PR https://github.com/ros/rosdistro/pull/14694 to remove this from Lunar as well as EOL on Kinetic.

**Comment by 130s** [comment]
@mikaelarguedas I'm very sorry, I was wrong. Looks like `household_objects_database_msgs` is only depended by `manipulation_msgs`, which is also EOLed. There seems no dependency from moveit.
